RNG_SEED: 777
SUBTR_MEANS: False
COLOR_SPACE: 'rgb'
NORM_COEFF: 1.0
PREPARE_SIZE: [108, 144]
INPUT_SHAPE: [96, 128]
CLS_TYPE: 'gender'
GPU_ID: 1
TRAIN:
  PRETRAINED: 'resnet-18'
  EPOCHS: 1
  SNAPSHOT_PERIOD: 100
  BATCH_SIZE: 128
  DEBUG_IMAGES: 'visualization/mxnet_exp1_hair_train_debug'
  DISTORT:
    USE_ROTATE: 1
    MAX_ROTATE: 15
    ROTATE_PROB: 0.5
    USE_SCALE: 1
    SCALE_MIN: 0.89
    SCALE_MAX: 1.125
    USE_DEFORM: 1
    MAX_DEFORM: 1.2
    USE_CROP: 1
    CROP_REGION: 0.75
    USE_JPEG: 0
    JPEG_PROB: 0.5
    USE_BRIGHTNESS: 1
    BRIGHTNESS_PROB: 0.1
    BRIGHT_MIN_ALPHA: 0.6
    BRIGHT_MAX_ALPHA: 1.66
    BRIGHT_MIN_BETA: -0.2
    BRIGHT_MAX_BETA: 0.2
    USE_GRAYSCALE: 0
    GRAYSCALE_PROB: 0.5
    USE_NOISE: 1
    NOISE_PROB: 0.25
    NOISE_SIGMA: 0.05
    USE_LOW_RES: 1
    LOW_RES_PROB: 0.25
VALIDATION:
  # DEBUG_IMAGES: '/home/ubuntu/projects/data/visualization/exp133_resnet_hair_val_debug'
  BATCH_SIZE: 64
  INTERVAL: 200
TEST:
  BATCH_SIZE: 64
  SHOW_CMAT: True
