RNG_SEED: 777
SUBTR_MEANS: False
COLOR_SPACE: 'rgb'
NORM_COEFF: 1.0
PREPARE_SIZE: [108, 144]
INPUT_SHAPE: [96, 128]
CLS_TYPE: 'gender'
GPU_ID: 3
TRAIN:
  # PRETRAINED: 'resnet-18'
  EPOCHS: 50
  SNAPSHOT_PERIOD: 99
  BATCH_SIZE: 128
  DISPLAY_ITERS: 3
  DEBUG_IMAGES: 'visualization/train_debug'
  DISTORT:
    USE_ROTATE: 1
    MAX_ROTATE: 15
    ROTATE_PROB: 0.5
    USE_SCALE: 1
    SCALE_MIN: 0.89
    SCALE_MAX: 1.125
    USE_DEFORM: 1
    MAX_DEFORM: 1.2
    USE_CROP: 1
    CROP_REGION: 0.75
    USE_JPEG: 0
    JPEG_PROB: 0.5
    USE_BRIGHTNESS: 1
    BRIGHTNESS_PROB: 0.1
    BRIGHT_MIN_ALPHA: 0.6
    BRIGHT_MAX_ALPHA: 1.66
    BRIGHT_MIN_BETA: -0.2
    BRIGHT_MAX_BETA: 0.2
    USE_GRAYSCALE: 0
    GRAYSCALE_PROB: 0.5
    USE_NOISE: 1
    NOISE_PROB: 0.25
    NOISE_SIGMA: 0.05
    USE_LOW_RES: 1
    LOW_RES_PROB: 0.25
VALIDATION:
  DEBUG_IMAGES: 'visualization/val_debug'
  BATCH_SIZE: 64
  INTERVAL: 10
TEST:
  DEBUG_IMAGES: 'visualization/test_debug'
  BATCH_SIZE: 64
  SHOW_CMAT: True
